theme: jekyll-theme-cayman
title: SARS-CoV-2 variants
description: Open-source tracking for emerging SARS-CoV-2 variants that pose a risk based on COVID-19 vaccine genetics.
google_analytics: UA-199638391-1
# gems:

# This will only work when built on githubpages, I think. Not locally.
url: https://sarscov2variants.com # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jemoji
